rm /usr/home/jracine/R/np/.svn/tmp/tempfile.2.tmp
rm /usr/home/jracine/R/np/.svn/tmp/tempfile.3.tmp
rm /usr/home/jracine/R/np/.svn/tmp/tempfile.tmp
rm /usr/home/jracine/R/np/src/.svn/tmp/tempfile.tmp
rm /usr/home/jracine/tex/categorical/ate/work/simul/x1_z1/n_100/tau_0.0/freq.tmp
rm /usr/home/jracine/tex/categorical/ate/work/simul/x1_z1/n_100/tau_0.0/sf.tmp
rm /usr/home/jracine/tex/categorical/c/work/fair_1977/train_eval/c.tmp
rm /usr/home/jracine/tex/categorical/mixed_data_chesg_talk/examples/nls_growth/quantile_hsa/quantile.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.00/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.00/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.00/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.25/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.25/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.25/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.50/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.50/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.50/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.75/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.75/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul/rho_0.75/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.00/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.00/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.00/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.25/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.25/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.25/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.50/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.50/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.50/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.75/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.75/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.75/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.95/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.95/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all/rho_0.95/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.00/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.00/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.00/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.25/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.25/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.25/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.50/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.50/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.50/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.75/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.75/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.75/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.95/n_100/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.95/n_250/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/regression_irrelevant/work/simul_corr_all_nonlinear/rho_0.95/n_500/sf_reg.tmp
rm /usr/home/jracine/tex/categorical/union/union.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata/col1.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata/p_vals.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata/sh.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata/table.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/col1.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/p_vals.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/pct_vals.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/sh.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/sh_pct.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/srho_vals.tmp
rm /usr/home/jracine/tex/entropy_specification/work/TRdata_rsq/table.tmp
rm /usr/home/jracine/tex/granger_maasoumi/refs.tmp
rm /usr/home/jracine/tex/housing/work_backup/lc/data.tmp
rm /usr/home/jracine/tex/housing/work_backup/ll/data.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/anglin_gencay_mls/R/PL_train_eval_500_46/col_names.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/anglin_gencay_mls/R/PL_train_eval_500_46/shuffle.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/anglin_gencay_mls/R/PL_train_eval_525_21/col_names.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/anglin_gencay_mls/R/PL_train_eval_525_21/shuffle.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/con_den/col1.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/con_den/col2.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/con_den_age_median/col1.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/con_den_age_median/col2.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/con_den_age_median_boot/col1.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/con_den_age_median_boot/col2.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/fair_wells_2003/train_eval_un_or/c.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/growthcharts/quantile_bsa/quantile.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/growthcharts/quantile_hsa/quantile.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/growthcharts/quantile_wsa/quantile.tmp
rm /usr/home/jracine/tex/li_racine_book/examples/growthcharts/quantile_wsh/quantile.tmp
rm /usr/home/jracine/tex/millimet/work/yrs/R/joint/stepBIC.tmp
rm /usr/home/jracine/tex/millimet/work/yrs/R/joint_bak/stepBIC.tmp
