#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(npRmpi))

is.master <- isTRUE(npRmpi.init(mode = "attach", quiet = TRUE))

if (is.master) {
  suppressPackageStartupMessages(library(MASS))
  set.seed(42)
  n <- 80
  x <- runif(n)
  z <- runif(n)
  y <- sin(2 * pi * x) + 0.5 * z + rnorm(n, sd = 0.1)
  d <- data.frame(x = x, y = y)
  d1 <- data.frame(x = x)
  d2 <- data.frame(x = x, z = z)
  dz <- data.frame(z = z)
  bw <- npregbw(y ~ x, data = d, regtype = "lc", bwmethod = "cv.ls", nmulti = 1)
  fit <- npreg(bws = bw, data = d, gradients = FALSE)
  bw.sc <- npscoefbw(xdat = d1, ydat = y, zdat = dz, regtype = "lc", nmulti = 1)
  fit.sc <- npscoef(bws = bw.sc, gradients = FALSE)
  bw.pl <- npplregbw(xdat = d1, ydat = y, zdat = dz, regtype = "lc", nmulti = 1)
  fit.pl <- npplreg(bws = bw.pl, gradients = FALSE)
  bw.si <- npindexbw(xdat = d2, ydat = y, regtype = "lc", nmulti = 1)
  fit.si <- npindex(bws = bw.si, gradients = FALSE)
  d.cop <- data.frame(x = x, y = y)
  u.cop <- data.frame(x = c(0.25, 0.5, 0.75), y = c(0.25, 0.5, 0.75))
  bw.cop <- npudistbw(~x + y, data = d.cop)
  cop <- npcopula(bws = bw.cop, data = d.cop, u = u.cop, n.quasi.inv = 60)
  data(birthwt)
  bdat <- birthwt
  bdat$low <- factor(bdat$low)
  bdat$smoke <- factor(bdat$smoke)
  bdat$race <- factor(bdat$race)
  bdat$ht <- factor(bdat$ht)
  bdat$ui <- factor(bdat$ui)
  bdat$ftv <- ordered(bdat$ftv)
  bw.cm <- npcdensbw(low ~ smoke + race + ht + ui + ftv + age + lwt, data = bdat, nmulti = 1)
  fit.cm <- npconmode(bws = bw.cm)
  stopifnot(inherits(fit, "npregression"))
  stopifnot(inherits(fit.sc, "smoothcoefficient"))
  stopifnot(inherits(fit.pl, "plregression"))
  stopifnot(inherits(fit.si, "singleindex"))
  stopifnot(inherits(cop, "data.frame"))
  stopifnot(nrow(cop) == 9L)
  stopifnot(all(is.finite(cop$copula)))
  stopifnot(inherits(fit.cm, "conmode"))
  cat("ATTACH_NPCONMODE_ROUTE_OK\n")
  cat("ATTACH_NPCOPULA_ROUTE_OK\n")
  cat("ATTACH_ROUTE_OK\n")
  npRmpi.quit(mode = "attach")
}
