test_that("local MPI dimension creation validates its native buffer", {
  skip_if_not(spawn_mpi_slaves(1L), "MPI pool unavailable")
  on.exit(close_mpi_slaves(force = TRUE), add = TRUE)
  native <- function(nnodes, ndims, dims)
    .Call("mpi_dims_create", nnodes, ndims, dims, PACKAGE = "npRmpi")

  for (bad in list(integer(), NA_integer_, c(1L, 2L), 1, "1"))
    expect_error(native(bad, 2L, integer(2)), "'nnodes'.*integer scalar")
  for (bad in list(integer(), NA_integer_, -1L, c(1L, 2L), 1, "1"))
    expect_error(native(6L, bad, integer(2)), "'ndims'.*integer scalar")
  expect_error(native(6L, 2L, integer(1)), "'dims'.*length at least 'ndims'")
  expect_error(native(1L, 10001L, integer(10000)), "'dims'.*length at least 'ndims'")
  expect_error(native(6L, 2L, numeric(2)), "'dims'.*integer vector")
  expect_identical(native(6L, 2L, integer(2)), c(3L, 2L))
  expect_identical(native(6L, 3L, c(0L, 3L, 0L)), c(2L, 3L, 1L))
  expect_identical(native(7L, 2L, integer(2)), c(7L, 1L))
  expect_identical(native(6L, 2L, c(0L, 0L, 77L)), c(3L, 2L, 77L))
  expect_identical(native(1L, 0L, integer()), integer())
  expect_identical(mpi.dims.create(6, 2), c(3L, 2L))
})
