test_that("session-route object-fed plot paths avoid public estimator re-entry", {
  skip_on_cran()
  env <- npRmpi_subprocess_env()
  skip_if(is.null(env), "local npRmpi install unavailable for subprocess smoke")

  res <- npRmpi_run_rscript_subprocess(
    lines = c(
      "suppressPackageStartupMessages(library(npRmpi))",
      "with_public_trace_counter <- function(fun, expr) {",
      "  ns <- asNamespace('npRmpi')",
      "  ctr <- new.env(parent = emptyenv())",
      "  ctr$n <- 0L",
      "  trace(",
      "    what = fun,",
      "    where = ns,",
      "    tracer = bquote(assign('n', get('n', envir = .(ctr)) + 1L, envir = .(ctr))),",
      "    print = FALSE",
      "  )",
      "  on.exit(try(untrace(fun, where = ns), silent = TRUE), add = TRUE)",
      "  force(expr)",
      "  ctr$n",
      "}",
      "npRmpi.init(nslaves = 1, quiet = TRUE)",
      "on.exit(try(npRmpi.quit(), silent = TRUE), add = TRUE)",
      "set.seed(9410)",
      "n.reg <- 36L",
      "xdat.reg <- data.frame(x = runif(n.reg))",
      "ydat.reg <- sin(2 * pi * xdat.reg$x) + rnorm(n.reg, sd = 0.05)",
      "bw.reg <- npregbw(xdat = xdat.reg, ydat = ydat.reg, regtype = 'lc', nmulti = 1)",
      "fit.reg <- npreg(txdat = xdat.reg, tydat = ydat.reg, bws = bw.reg)",
      "calls <- with_public_trace_counter('npreg', {",
      "  out.bw <- plot(bw.reg, xdat = xdat.reg, ydat = ydat.reg, plot.behavior = 'data')",
      "  out.fit <- plot(fit.reg, xdat = xdat.reg, ydat = ydat.reg, plot.behavior = 'data')",
      "  stopifnot(is.list(out.bw), is.list(out.fit))",
      "})",
      "stopifnot(identical(calls, 0L))",
      "set.seed(9411)",
      "n <- 30L",
      "dat <- data.frame(x = runif(n))",
      "dens.bw <- npudensbw(dat = dat, bws = 0.18, bandwidth.compute = FALSE, bwtype = 'fixed')",
      "dist.bw <- npudistbw(dat = dat, bws = 0.18, bandwidth.compute = FALSE, bwtype = 'fixed')",
      "dens.fit <- npudens(tdat = dat, bws = dens.bw)",
      "dist.fit <- npudist(tdat = dat, bws = dist.bw)",
      "dens.calls <- with_public_trace_counter('npudens', {",
      "  out.bw <- plot(dens.bw, xdat = dat, plot.behavior = 'data')",
      "  out.fit <- plot(dens.fit, xdat = dat, plot.behavior = 'data')",
      "  stopifnot(is.list(out.bw), is.list(out.fit))",
      "})",
      "dist.calls <- with_public_trace_counter('npudist', {",
      "  out.bw <- plot(dist.bw, xdat = dat, plot.behavior = 'data')",
      "  out.fit <- plot(dist.fit, xdat = dat, plot.behavior = 'data')",
      "  stopifnot(is.list(out.bw), is.list(out.fit))",
      "})",
      "stopifnot(identical(dens.calls, 0L), identical(dist.calls, 0L))",
      "set.seed(94115)",
      "n.qr <- 20L",
      "xdat.qr <- data.frame(x = runif(n.qr))",
      "ydat.qr <- data.frame(y = sin(2 * pi * xdat.qr$x) + rnorm(n.qr, sd = 0.05))",
      "bw.qr <- npcdistbw(xdat = xdat.qr, ydat = ydat.qr, bws = c(0.25, 0.25), bandwidth.compute = FALSE)",
      "fit.qr <- npqreg(bws = bw.qr, txdat = xdat.qr, tydat = ydat.qr, tau = 0.4)",
      "qreg.calls <- with_public_trace_counter('npqreg', {",
      "  out.bw.fixed <- plot(bw.qr, xdat = xdat.qr, ydat = ydat.qr, plot.behavior = 'data', perspective = TRUE, view = 'fixed', quantreg = TRUE, tau = 0.4, neval = 6)",
      "  out.fit.fixed <- plot(fit.qr, plot.behavior = 'data', perspective = TRUE, view = 'fixed', neval = 6)",
      "  out.bw.slice <- plot(bw.qr, xdat = xdat.qr, ydat = ydat.qr, plot.behavior = 'data', perspective = FALSE, quantreg = TRUE, tau = 0.4, neval = 6)",
      "  out.fit.slice <- plot(fit.qr, plot.behavior = 'data', perspective = FALSE, neval = 6)",
      "  stopifnot(is.list(out.bw.fixed), is.list(out.fit.fixed), is.list(out.bw.slice), is.list(out.fit.slice))",
      "})",
      "stopifnot(identical(qreg.calls, 0L))",
      "set.seed(94114)",
      "xdat.sc <- data.frame(x = runif(24L))",
      "zdat.sc <- data.frame(z = runif(24L))",
      "ydat.sc <- 1.2 * xdat.sc$x + cos(2 * pi * zdat.sc$z) + rnorm(24L, sd = 0.05)",
      "bw.sc <- npscoefbw(xdat = xdat.sc, zdat = zdat.sc, ydat = ydat.sc, regtype = 'lc', nmulti = 1)",
      "fit.sc <- npscoef(txdat = xdat.sc, tzdat = zdat.sc, tydat = ydat.sc, bws = bw.sc, errors = FALSE, betas = TRUE)",
      "sc.calls <- with_public_trace_counter('npscoef', {",
      "  out.bw <- plot(bw.sc, xdat = xdat.sc, zdat = zdat.sc, ydat = ydat.sc, coef = TRUE, plot.behavior = 'data', perspective = FALSE)",
      "  out.fit <- plot(fit.sc, xdat = xdat.sc, zdat = zdat.sc, ydat = ydat.sc, coef = TRUE, plot.behavior = 'data', perspective = FALSE)",
      "  out.boot.bw <- suppressWarnings(plot(bw.sc, xdat = xdat.sc, zdat = zdat.sc, ydat = ydat.sc, coef = TRUE, plot.behavior = 'data', perspective = FALSE, plot.errors.method = 'bootstrap', plot.errors.boot.num = 12, plot.errors.boot.method = 'inid'))",
      "  out.boot.fit <- suppressWarnings(plot(fit.sc, xdat = xdat.sc, zdat = zdat.sc, ydat = ydat.sc, coef = TRUE, plot.behavior = 'data', perspective = FALSE, plot.errors.method = 'bootstrap', plot.errors.boot.num = 12, plot.errors.boot.method = 'inid'))",
      "  stopifnot(is.list(out.bw), is.list(out.fit), is.list(out.boot.bw), is.list(out.boot.fit))",
      "})",
      "stopifnot(identical(sc.calls, 0L))",
      "set.seed(9412)",
      "n <- 18L",
      "xdat <- data.frame(x = runif(n))",
      "zdat <- data.frame(z = runif(n))",
      "ydat <- 1.5 * xdat$x + cos(2 * pi * zdat$z) + rnorm(n, sd = 0.05)",
      "bw <- npplregbw(xdat = xdat, ydat = ydat, zdat = zdat, regtype = 'lc', nmulti = 1)",
      "fit <- npplreg(txdat = xdat, tydat = ydat, tzdat = zdat, bws = bw)",
      "calls <- with_public_trace_counter('npplreg', {",
      "  out.bw <- plot(bw, xdat = xdat, ydat = ydat, zdat = zdat, coef = TRUE, plot.behavior = 'data', perspective = FALSE)",
      "  out.fit <- plot(fit, xdat = xdat, ydat = ydat, zdat = zdat, coef = TRUE, plot.behavior = 'data', perspective = FALSE)",
      "  stopifnot(is.list(out.bw), is.list(out.fit))",
      "})",
      "stopifnot(identical(calls, 0L))",
      "set.seed(9413)",
      "n <- 32L",
      "xdat <- data.frame(x1 = runif(n), x2 = runif(n))",
      "ydat <- sin(xdat$x1 + xdat$x2) + rnorm(n, sd = 0.05)",
      "bw <- npindexbw(xdat = xdat, ydat = ydat, method = 'ichimura', nmulti = 1)",
      "fit <- npindex(txdat = xdat, tydat = ydat, bws = bw)",
      "calls <- with_public_trace_counter('npindex', {",
      "  out.bw <- plot(bw, xdat = xdat, ydat = ydat, plot.behavior = 'data')",
      "  out.fit <- plot(fit, xdat = xdat, ydat = ydat, plot.behavior = 'data')",
      "  stopifnot(is.list(out.bw), is.list(out.fit))",
      "})",
      "stopifnot(identical(calls, 0L))",
      "cat('PLOT_RUNTIME_PURITY_OK\\n')"
    ),
    timeout = 60L,
    env = env
  )

  expect_equal(res$status, 0L, info = paste(res$output, collapse = "\n"))
  expect_true(any(grepl("PLOT_RUNTIME_PURITY_OK", res$output, fixed = TRUE)),
              info = paste(res$output, collapse = "\n"))
})
