test_that("conditional generalized-NN full fits use exact query geometry", {
  env <- npRmpi_subprocess_env(c("NP_RMPI_NO_REUSE_SLAVES=1"))
  skip_if(is.null(env), "installed npRmpi unavailable for subprocess proof")
  nslaves <- as.integer(Sys.getenv("NP_RMPI_GNN_GEOMETRY_TEST_NSLAVES", "1"))
  stopifnot(nslaves %in% c(1L, 3L))
  ok_tag <- "NPRMPI_CONDITIONAL_GNN_FULLFIT_GEOMETRY_OK"
  lines <- c(
    "suppressPackageStartupMessages(library(npRmpi))",
    "options(npRmpi.autodispatch=TRUE, npRmpi.reuse.slaves=FALSE, np.messages=FALSE, np.tree=FALSE)",
    sprintf("npRmpi.init(nslaves=%dL, quiet=TRUE)", nslaves),
    "on.exit(try(npRmpi.quit(force=TRUE), silent=TRUE), add=TRUE)",
    "radius <- function(train,evaluation,k,excluded=integer()) {",
    "  keep <- if (length(excluded)) setdiff(seq_along(train),excluded) else seq_along(train)",
    "  sort(abs(train[keep]-evaluation),method='radix')[[k]]",
    "}",
    "oracle <- function(x,y,kx,ky,degree=0L,distribution=FALSE,evaluation=NULL) {",
    "  x <- as.matrix(x); y <- as.numeric(y)",
    "  ex <- if (is.null(evaluation)) x else as.matrix(evaluation$x)",
    "  ey <- if (is.null(evaluation)) y else as.numeric(evaluation$y)",
    "  eval_to_train <- if (is.null(evaluation)) seq_len(nrow(x)) else rep.int(NA_integer_,nrow(ex))",
    "  vapply(seq_len(nrow(ex)),function(i) {",
    "    excluded <- if (is.na(eval_to_train[[i]])) integer() else eval_to_train[[i]]",
    "    hx <- vapply(seq_len(ncol(x)),function(l) radius(x[,l],ex[i,l],kx[[l]],excluded),numeric(1L))",
    "    hy <- radius(y,ey[[i]],ky,excluded)",
    "    wx <- rep.int(1,nrow(x))",
    "    for (l in seq_len(ncol(x))) wx <- wx*dnorm((ex[i,l]-x[,l])/hx[[l]])/hx[[l]]",
    "    yrow <- if (distribution) pnorm((ey[[i]]-y)/hy) else dnorm((ey[[i]]-y)/hy)/hy",
    "    if (degree==0L) influence <- wx/sum(wx) else {",
    "      design <- cbind(1,x[,1L]-ex[i,1L])",
    "      influence <- drop(c(1,0)%*%solve(crossprod(design,wx*design),t(design)*rep(wx,each=2L)))",
    "    }",
    "    sum(influence*yrow)",
    "  },numeric(1L))",
    "}",
    "make_bw <- function(x,y,kx,ky,degree=0L,distribution=FALSE) {",
    "  args <- list(xdat=as.data.frame(x),ydat=data.frame(y=y),bws=c(ky,kx),bandwidth.compute=FALSE,bwmethod=if(distribution)'cv.ls' else 'cv.ml',bwtype='generalized_nn',bwscaling=FALSE,cxkertype='gaussian',cykertype='gaussian',regtype=if(degree==0L)'lc' else 'lp')",
    "  if (distribution) args$ngrid <- 7L",
    "  if (degree>0L) {args$basis <- 'glp'; args$degree <- rep.int(degree,ncol(as.matrix(x)))}",
    "  do.call(if(distribution) npcdistbw else npcdensbw,args)",
    "}",
    "fit_values <- function(x,y,bw,distribution=FALSE,evaluation=NULL) {",
    "  args <- list(bws=bw,txdat=as.data.frame(x),tydat=data.frame(y=y))",
    "  if (!is.null(evaluation)) {args$exdat <- as.data.frame(evaluation$x); args$eydat <- data.frame(y=evaluation$y)}",
    "  fit <- do.call(if(distribution) npcdist else npcdens,args)",
    "  if (distribution) fit$condist else fit$condens",
    "}",
    "set.seed(20260818); n <- 13L",
    "x1 <- sort(runif(n,-0.9,1.1)); x2 <- runif(n,-0.6,0.8)",
    "y <- 0.8*x1-0.35*x2+rnorm(n,sd=0.17)",
    "cases <- list(lc1=list(x=data.frame(x1=x1),kx=4L,ky=5L,degree=0L),lc2=list(x=data.frame(x1=x1,x2=x2),kx=c(4L,6L),ky=5L,degree=0L),ll1=list(x=data.frame(x1=x1),kx=6L,ky=5L,degree=1L))",
    "for (case_name in names(cases)) {",
    "  case <- cases[[case_name]]",
    "  for (distribution in c(FALSE,TRUE)) {",
    "    expected <- oracle(case$x,y,case$kx,case$ky,case$degree,distribution)",
    "    bw <- make_bw(case$x,y,case$kx,case$ky,case$degree,distribution)",
    "    for (tree in c(FALSE,TRUE)) {",
    "      options(np.tree=tree)",
    "      observed <- fit_values(case$x,y,bw,distribution)",
    "      if (!isTRUE(all.equal(observed,expected,tolerance=2e-10))) stop(sprintf('%s distribution=%s tree=%s differs from oracle',case_name,distribution,tree))",
    "    }",
    "  }",
    "}",
    "xext <- data.frame(x=sort(runif(13L,-0.9,1.1)))",
    "yext <- 0.8*xext$x+rnorm(13L,sd=0.17)",
    "evaluation <- list(x=xext[c(2L,7L,12L),,drop=FALSE],y=yext[c(2L,7L,12L)])",
    "bwext <- make_bw(xext,yext,4L,5L)",
    "expected_ext <- oracle(xext,yext,4L,5L,evaluation=evaluation)",
    "observed_ext <- fit_values(xext,yext,bwext,evaluation=evaluation)",
    "stopifnot(isTRUE(all.equal(observed_ext,expected_ext,tolerance=2e-12)))",
    "for (distribution in c(FALSE,TRUE)) {",
    "  bw <- make_bw(xext,yext,6L,5L,1L,distribution)",
    "  fits <- lapply(c(FALSE,TRUE),function(tree) {",
    "    options(np.tree=tree)",
    "    do.call(if(distribution) npcdist else npcdens,list(bws=bw,txdat=xext,tydat=data.frame(y=yext),gradients=TRUE))",
    "  })",
    "  fields <- c(if(distribution)'condist' else 'condens','conderr','congrad','congerr')",
    "  for (field in fields) {",
    "    stopifnot(all(is.finite(fits[[1L]][[field]])))",
    "    if (!isTRUE(all.equal(fits[[2L]][[field]],fits[[1L]][[field]],tolerance=2e-10))) stop(sprintf('%s tree uncertainty parity failed',field))",
    "  }",
    "}",
    "xdup <- data.frame(x=c(0,0,0,1,2)); ydup <- c(0,0,0,0.5,1)",
    "for (degree in 0:1) {",
    "  bwdup <- make_bw(xdup,ydup,2L,2L,degree)",
    "  message <- tryCatch({fit_values(xdup,ydup,bwdup); NA_character_},error=function(e) conditionMessage(e))",
    "  stopifnot(is.character(message),length(message)==1L,grepl('zero literal.*radius after occurrence exclusion',message))",
    "}",
    sprintf("cat('%s\\n')", ok_tag)
  )
  result <- npRmpi_run_rscript_subprocess(lines=lines, timeout=180L, env=env)
  info <- paste(result$output, collapse="\n")
  expect_equal(result$status, 0L, info=info)
  expect_true(any(grepl(ok_tag, result$output, fixed=TRUE)), info=info)
})
