test_that("empirical conditional-CDF CV uses exact pair-local geometry", {
  env <- npRmpi_subprocess_env(c("NP_RMPI_NO_REUSE_SLAVES=1"))
  skip_if(is.null(env), "installed npRmpi unavailable for subprocess proof")
  nslaves <- as.integer(Sys.getenv("NP_RMPI_GNN_GEOMETRY_TEST_NSLAVES", "1"))
  stopifnot(nslaves %in% c(1L, 3L))
  ok_tag <- "NPRMPI_CONDITIONAL_GNN_EMPIRICAL_CDF_OK"
  lines <- c(
    "suppressPackageStartupMessages(library(npRmpi))",
    "options(npRmpi.autodispatch=TRUE, npRmpi.reuse.slaves=FALSE, np.messages=FALSE, np.tree=FALSE, np.macMseries.accelerate=FALSE)",
    sprintf("npRmpi.init(nslaves=%dL, quiet=TRUE)", nslaves),
    "on.exit(try(npRmpi.quit(force=TRUE), silent=TRUE), add=TRUE)",
    "radius <- function(train,evaluation,k,excluded) {",
    "  keep <- setdiff(seq_along(train),excluded)",
    "  sort(abs(train[keep]-evaluation),method='radix')[[k]]",
    "}",
    "oracle <- function(x,y,kx,ky) {",
    "  x <- as.matrix(x); y <- as.matrix(y); n <- nrow(x); total <- 0",
    "  for (i in seq_len(n)) {",
    "    keep <- setdiff(seq_len(n),i)",
    "    hx <- vapply(seq_len(ncol(x)),function(d) radius(x[,d],x[i,d],kx[[d]],i),numeric(1L))",
    "    xrow <- rep.int(1,length(keep))",
    "    for (d in seq_len(ncol(x))) xrow <- xrow*dnorm((x[i,d]-x[keep,d])/hx[[d]])",
    "    xrow <- xrow/sum(xrow)",
    "    for (j in seq_len(n)) {",
    "      if (i==j) next",
    "      hy <- vapply(seq_len(ncol(y)),function(d) radius(y[,d],y[j,d],ky[[d]],c(i,j)),numeric(1L))",
    "      yrow <- rep.int(1,length(keep))",
    "      for (d in seq_len(ncol(y))) yrow <- yrow*pnorm((y[j,d]-y[keep,d])/hy[[d]])",
    "      fit <- sum(xrow*yrow); indicator <- as.integer(all(y[i,]<=y[j,]))",
    "      total <- total+(indicator-fit)^2",
    "    }",
    "  }",
    "  total/(n*(n-1L))",
    "}",
    "native <- function(x,y,kx,ky,tree) {",
    "  options(np.tree=tree)",
    "  bw <- npcdistbw(xdat=as.data.frame(x),ydat=as.data.frame(y),bws=c(ky,kx),bandwidth.compute=FALSE,bwmethod='cv.ls',bwtype='generalized_nn',bwscaling=FALSE,cxkertype='gaussian',cykertype='gaussian',regtype='lc')",
    "  npRmpi:::.npcdistbw_eval_only(as.data.frame(x),as.data.frame(y),bws=bw,do.full.integral=TRUE)$objective[[1L]]",
    "}",
    "set.seed(20260822); n <- 9L",
    "x <- data.frame(x=sort(runif(n,-0.9,1.1)))",
    "y <- data.frame(y=0.55*x$x+rnorm(n,sd=0.23))",
    "expected <- oracle(x,y,3L,4L)",
    "observed <- vapply(c(FALSE,TRUE),function(tree) native(x,y,3L,4L,tree),numeric(1L))",
    "stopifnot(isTRUE(all.equal(observed,rep(expected,2L),tolerance=5e-10)),identical(observed[[1L]],observed[[2L]]))",
    "set.seed(20260823); n <- 9L",
    "x <- data.frame(x=sort(runif(n,-0.7,0.8)))",
    "y <- data.frame(y1=0.4*x$x+rnorm(n,sd=0.18),y2=-0.2*x$x+rnorm(n,sd=0.21))",
    "expected <- oracle(x,y,3L,c(3L,4L))",
    "observed <- vapply(c(FALSE,TRUE),function(tree) native(x,y,3L,c(3L,4L),tree),numeric(1L))",
    "stopifnot(isTRUE(all.equal(observed,rep(expected,2L),tolerance=8e-10)),identical(observed[[1L]],observed[[2L]]))",
    "x <- data.frame(x=c(-0.8,-0.8,-0.25,0,0,0.31,0.55,0.55,0.82,1.05))",
    "y <- data.frame(y=c(-0.4,-0.4,-0.08,0.12,0.12,0.34,0.48,0.48,0.73,0.9))",
    "expected <- oracle(x,y,3L,3L)",
    "observed <- vapply(c(FALSE,TRUE),function(tree) native(x,y,3L,3L,tree),numeric(1L))",
    "stopifnot(isTRUE(all.equal(observed,rep(expected,2L),tolerance=2e-10)),identical(observed[[1L]],observed[[2L]]))",
    "set.seed(20260825); n <- 10L",
    "x <- data.frame(x=sort(runif(n,-0.8,1)))",
    "y <- data.frame(y=0.6*x$x+rnorm(n,sd=0.24)); saturated_k <- n-2L",
    "expected <- oracle(x,y,3L,saturated_k)",
    "observed <- vapply(c(FALSE,TRUE),function(tree) native(x,y,3L,saturated_k,tree),numeric(1L))",
    "stopifnot(isTRUE(all.equal(observed,rep(expected,2L),tolerance=2e-9)),identical(observed[[1L]],observed[[2L]]))",
    "set.seed(20260824); n <- 8L",
    "x <- data.frame(x=runif(n)); y <- data.frame(y=0.3*x$x+rnorm(n,sd=0.2))",
    "bw <- npcdistbw(xdat=x,ydat=y,bws=c(0.31,0.43),bandwidth.compute=FALSE,bwmethod='cv.ls',bwtype='fixed',bwscaling=FALSE,cxkertype='gaussian',cykertype='gaussian',regtype='lc')",
    "objective <- npRmpi:::.npcdistbw_eval_only(x,y,bws=bw,do.full.integral=TRUE)$objective[[1L]]",
    "total <- 0",
    "for (i in seq_len(n)) {",
    "  keep <- setdiff(seq_len(n),i); xrow <- dnorm((x$x[[i]]-x$x[keep])/0.43); xrow <- xrow/sum(xrow)",
    "  for (j in seq_len(n)) {",
    "    if (i==j) next",
    "    fit <- sum(xrow*pnorm((y$y[[j]]-y$y[keep])/0.31))",
    "    total <- total+(as.integer(y$y[[i]]<=y$y[[j]])-fit)^2",
    "  }",
    "}",
    "stopifnot(isTRUE(all.equal(objective,total/(n*(n-1L)),tolerance=5e-10)))",
    "xb <- c(0.02,0.08,0.19,0.37,0.62,0.81,0.96)",
    "yb <- c(0.03,0.14,0.24,0.43,0.59,0.79,0.97); hx <- 0.17; hy <- 0.15",
    "wx <- npksum(txdat=data.frame(value=xb),exdat=data.frame(value=xb),bws=hx,bwtype='fixed',ckertype='beta',ckerorder=2L,operator='normal',return.kernel.weights=TRUE,ckerbound='fixed',ckerlb=0,ckerub=1)$kw",
    "wy <- npksum(txdat=data.frame(value=yb),exdat=data.frame(value=yb),bws=hy,bwtype='fixed',ckertype='beta',ckerorder=2L,operator='integral',return.kernel.weights=TRUE,ckerbound='fixed',ckerlb=0,ckerub=1)$kw",
    "beta_total <- 0",
    "for (i in seq_along(xb)) {",
    "  keep <- setdiff(seq_along(xb),i)",
    "  for (j in seq_along(yb)) {",
    "    if (i==j) next",
    "    fit <- sum(wx[keep,i]*wy[keep,j])/sum(wx[keep,i])",
    "    beta_total <- beta_total+(as.integer(yb[[i]]<=yb[[j]])-fit)^2",
    "  }",
    "}",
    "beta_bw <- npcdistbw(xdat=data.frame(x=xb),ydat=data.frame(y=yb),bws=c(hy,hx),bandwidth.compute=FALSE,bwmethod='cv.ls',bwtype='fixed',bwscaling=FALSE,cxkertype='beta',cxkerorder=2L,cxkerbound='fixed',cxkerlb=0,cxkerub=1,cykertype='beta',cykerorder=2L,cykerbound='fixed',cykerlb=0,cykerub=1)",
    "beta_objective <- npRmpi:::.npcdistbw_eval_only(data.frame(x=xb),data.frame(y=yb),bws=beta_bw,do.full.integral=TRUE)$objective[[1L]]",
    "stopifnot(isTRUE(all.equal(beta_objective,beta_total/(length(xb)*(length(xb)-1L)),tolerance=2e-10)))",
    "set.seed(20260822); n <- 9L",
    "x <- data.frame(x=sort(runif(n,-0.9,1.1)))",
    "y <- data.frame(y=0.55*x$x+rnorm(n,sd=0.23)); kx <- 3L; ky <- 4L",
    "mpi_expected <- oracle(x,y,kx,ky)",
    "mpi_bw <- npcdistbw(xdat=x,ydat=y,bws=c(ky,kx),bandwidth.compute=FALSE,bwmethod='cv.ls',bwtype='generalized_nn',bwscaling=FALSE,cxkertype='gaussian',cykertype='gaussian',regtype='lc')",
    "mpi_prep <- getFromNamespace('.npcdistbw_nomad_native_prepare_args','npRmpi')(xdat=x,ydat=y,bws=mpi_bw,do.full.integral=TRUE)",
    "mpi_cmd <- substitute(local({ options(np.objective.cache=FALSE); get('npNomadNativeSearchConditionalDistribution',envir=asNamespace('npRmpi'),inherits=FALSE)(prep=PREP,x0=X0,bbin=c(1L,1L),lb=c(1,1),ub=UPPER,max.eval=1L,random.seed=20260822L,inner.start.count=0L,option.names=character(),option.values=character()) }),list(PREP=mpi_prep,X0=c(ky,kx),UPPER=c(n-2L,n-1L)))",
    "mpi_native <- getFromNamespace('.npRmpi_bcast_cmd_expr','npRmpi')(mpi_cmd,comm=1L,caller.execute=TRUE)",
    "stopifnot(abs(as.numeric(mpi_native$first_objective[[1L]])-mpi_expected)<5e-10,as.integer(mpi_native$compiled_callback_calls[[1L]])>=1L,identical(as.integer(mpi_native$compiled_callback_failures[[1L]]),0L))",
    sprintf("cat('%s\\n')", ok_tag)
  )
  result <- npRmpi_run_rscript_subprocess(lines=lines, timeout=180L, env=env)
  info <- paste(result$output, collapse="\n")
  expect_equal(result$status, 0L, info=info)
  expect_true(any(grepl(ok_tag, result$output, fixed=TRUE)), info=info)
})
