#!/bin/bash
set -euo pipefail

for np in 2 3 4; do
  mkdir -p "n_${np}_attach"
  (
    cd "n_${np}_attach"
    make -f ../makefile.attach np=${np}
  )

  mkdir -p "n_${np}_profile"
  (
    cd "n_${np}_profile"
    make -f ../makefile.profile np=${np}
  )
done
