#!/bin/bash

## n=2

grep "n <- " serial/*serial.Rout | awk '{print $4}' > sample_serial.tmp
grep "time = " n_2/*npRmpi.Rout | awk -F/ '{print $2}' | awk -F_ '{print $1}' > names.tmp
grep "time = " n_2/*npRmpi.Rout | awk -F= '{print $2}' > npRmpi.tmp
grep "time = " serial/*serial.Rout | awk -F= '{print $2}' > serial.tmp

wc -l npRmpi.tmp > npRmpi_num.tmp
wc -l serial.tmp > serial_num.tmp

paste names.tmp sample_serial.tmp serial.tmp npRmpi.tmp | awk '{printf("%s (n=%d): np=1: %.1f, np=2: %.1f, ratio=%.2f\n", $1, $2, $3, $4, $4/$3)}' > timing_n_2.dat

echo '\begin{tabular}{llrrr}' > timing_n_2.tex
echo 'Function & $n$ & Secs(1) & Secs(2) & Ratio\cr' >> timing_n_2.tex
echo '\hline' >> timing_n_2.tex
paste names.tmp sample_serial.tmp serial.tmp npRmpi.tmp | awk '{printf("%s & %d & %.1f & %.1f & %.2f\\cr\n", $1, $2, $3, $4, $4/$3)}' >> timing_n_2.tex
echo '\hline' >> timing_n_2.tex
echo '\end{tabular}' >> timing_n_2.tex

cat timing_n_2.dat

paste npRmpi_num.tmp serial_num.tmp | awk '{if($1!=$3) print("Number of runs unequal, table invalid")}'

rm *.tmp

## n=3

grep "n <- " serial/*serial.Rout | awk '{print $4}' > sample_serial.tmp
grep "time = " n_3/*npRmpi.Rout | awk -F/ '{print $2}' | awk -F_ '{print $1}' > names.tmp
grep "time = " n_3/*npRmpi.Rout | awk -F= '{print $2}' > npRmpi.tmp
grep "time = " serial/*serial.Rout | awk -F= '{print $2}' > serial.tmp

wc -l npRmpi.tmp > npRmpi_num.tmp
wc -l serial.tmp > serial_num.tmp

paste names.tmp sample_serial.tmp serial.tmp npRmpi.tmp | awk '{printf("%s (n=%d): np=1: %.1f, np=2: %.1f, ratio=%.2f\n", $1, $2, $3, $4, $4/$3)}' > timing_n_3.dat

echo '\begin{tabular}{llrrr}' > timing_n_3.tex
echo 'Function & $n$ & Secs(1) & Secs(3) & Ratio\cr' >> timing_n_3.tex
echo '\hline' >> timing_n_3.tex
paste names.tmp sample_serial.tmp serial.tmp npRmpi.tmp | awk '{printf("%s & %d & %.1f & %.1f & %.2f\\cr\n", $1, $2, $3, $4, $4/$3)}' >> timing_n_3.tex
echo '\hline' >> timing_n_3.tex
echo '\end{tabular}' >> timing_n_3.tex

cat timing_n_3.dat

paste npRmpi_num.tmp serial_num.tmp | awk '{if($1!=$3) print("Number of runs unequal, table invalid")}'

rm *.tmp

## n=4

grep "n <- " serial/*serial.Rout | awk '{print $4}' > sample_serial.tmp
grep "time = " n_4/*npRmpi.Rout | awk -F/ '{print $2}' | awk -F_ '{print $1}' > names.tmp
grep "time = " n_4/*npRmpi.Rout | awk -F= '{print $2}' > npRmpi.tmp
grep "time = " serial/*serial.Rout | awk -F= '{print $2}' > serial.tmp

wc -l npRmpi.tmp > npRmpi_num.tmp
wc -l serial.tmp > serial_num.tmp

paste names.tmp sample_serial.tmp serial.tmp npRmpi.tmp | awk '{printf("%s (n=%d): np=1: %.1f, np=2: %.1f, ratio=%.2f\n", $1, $2, $3, $4, $4/$3)}' > timing_n_4.dat

echo '\begin{tabular}{llrrr}' > timing_n_4.tex
echo 'Function & $n$ & Secs(1) & Secs(4) & Ratio\cr' >> timing_n_4.tex
echo '\hline' >> timing_n_4.tex
paste names.tmp sample_serial.tmp serial.tmp npRmpi.tmp | awk '{printf("%s & %d & %.1f & %.1f & %.2f\\cr\n", $1, $2, $3, $4, $4/$3)}' >> timing_n_4.tex
echo '\hline' >> timing_n_4.tex
echo '\end{tabular}' >> timing_n_4.tex

cat timing_n_4.dat

paste npRmpi_num.tmp serial_num.tmp | awk '{if($1!=$3) print("Number of runs unequal, table invalid")}'

rm *.tmp

latexmk -pdf timing
